# Generated by Django 5.1.7 on 2025-03-25 13:37

import django.core.validators
import user.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_middle_name_alter_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.profile.avatar_upload_to, validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
